version: '3.9'

services:
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile.arm
    hostname: api1
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/rinhadb
      - DATABASE_USERNAME=rinhaapp
      - DATABASE_PASSWORD=root
#    depends_on:
#      db-postgresql:
#        condition: service_healthy
    ports:
      - "8080:8080"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '550MB'
    networks:
      - app-network
#    healthcheck:
#      test: curl -o /dev/null -s --retry 0 --get http://localhost:8080/health-check || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 5s

networks:
  app-network: