FROM --platform=arm64 registry.access.redhat.com/ubi8/openjdk-21

WORKDIR /app
CMD ["ls"]
COPY target/hello-virtual-threads-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java","-XX:+UseParallelGC","-server","-XX:InitialRAMPercentage=75", "-XX:MaxRAMPercentage=75", "-jar", "app.jar"]
